apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gloo-edge
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/solo-io/gloo-gitops'
    path: cluster-common/gloo-edge
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: gloo-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true