apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali-helm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kiali-operator
  project: default
  source:
    chart: kiali-operator
    repoURL: https://kiali.org/helm-charts
    targetRevision: 1.29.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true