---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gloo
    gloo: gateway-proxy
    gateway-proxy-id: gateway-proxy
  name: gateway-proxy-headless
  namespace: gloo-system
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: 8081
  selector:
    gateway-proxy: live
    gateway-proxy-id: gateway-proxy
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: gloo
    gateway-proxy-id: gateway-proxy
    gloo: gateway-proxy
    monitoring: gateway-proxy
    release: prom
  name: gateway-proxy
  namespace: prometheus
spec:
  jobLabel: gateway-proxy
  targetLabels: [app]
  endpoints:
  - path: /metrics
    port: metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - gloo-system
  selector:
    matchLabels:
      gloo: gateway-proxy
      gateway-proxy-id: gateway-proxy




